### ISSUE TITLE
Prusa slicer has no mount-observe plug anymore.

### ISSUE THREAD

**Issue by rcludwick** [ivocavalcante/PrusaSlicer-snap#12]
This used to work 2.5.x and is mentioned in the snapcraft store.

Maybe update the docs? 

```
$ sudo snap connect prusa-slicer:mount-observe
error: snap "prusa-slicer" has no plug named "mount-observe"
```

**Comment by ivocavalcante** [comment]
Hi,

Thanks for pointing out. For this release, I adjusted the package to use `gnome` extension which, according to [docs](https://snapcraft.io/docs/gnome-extension), would provide this plug. Seems either I got it wrong or doc isn't correct. I'll release a new version re-enabling this plug, since it eliminates some error messages.
